"""Init

Revision ID: 25e5a7e8c2e2
Revises: 
Create Date: 2025-12-01 10:30:41.037242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '25e5a7e8c2e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Проверяем существование типа перед созданием
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'socialnetwork')"
    )).scalar()
    
    if not result:
        # Создаем enum с правильными значениями только если его нет
        social_enum = postgresql.ENUM('vk', 'io', 'gg', 'pi', name='socialnetwork', create_type=True)
        social_enum.create(connection)
    
    # Используем существующий или только что созданный enum
    social_enum = postgresql.ENUM('vk', 'io', 'gg', 'pi', name='socialnetwork', create_type=False)
    
    # Проверяем существование таблиц перед созданием
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'accounts' not in existing_tables:
        op.create_table('accounts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('social', social_enum, nullable=False),
            sa.Column('account_id', sa.String(), nullable=False),
            sa.Column('account_type', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=True),
            sa.Column('photo', sa.String(), nullable=True),
            sa.Column('smmbox_group_id', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    
    if 'posts' not in existing_tables:
        op.create_table('posts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('account_id', sa.Integer(), nullable=False),
            sa.Column('video_url', sa.String(), nullable=False),
            sa.Column('smmbox_post_id', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.execute("DROP TYPE IF EXISTS socialnetwork;")
    # ### end Alembic commands ###

